org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2,27)
neo_version=26.1.2.95
neo_version_range=[26,)

mod_id=pickable_orbs
mod_name=Pickable Orbs
mod_license=All Rights Reserved
mod_version=26.1.2-1.0.1
mod_group_id=com.decursioteam
mod_authors=Decursio Team
mod_description=Pickable Orbs
